//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housekeeping
    {
        public int HousekeepingId { get; set; }
        public string RoomNumber { get; set; }
        public int EmployeeId { get; set; }
        public int HousekeepingStatusId { get; set; }
        public string HousekeepingNote { get; set; }
    }
}
