//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousekeepingStatus
    {
        public int HousekeepingStatusId { get; set; }
        public string HousekeepingStatus1 { get; set; }
    }
}
